name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://xxx/api/v1/ci-start'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: >-
            {
              "env": "prod",
              "project_name": "_username_-_app-name_",
              "src_path": "~/src/_username_/_app-name_",
              "token": "${{ secrets.TOKEN }}",
              "port": 0,
              "config_path": "~/data/_username_/_app-name_-prod",
              "alert_tg_token": "",
              "alert_tg_group_id": "",
              "loki_url": ""
            }

